nelmio_api_doc:
    documentation:
        info:
            title: Mon API de Cinéma
            description: Cette API permet la réservation de séance de cinéma !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc